Document authentication
dalibo/pg_activity pull request #254
Opened 2021-12-02 16:40 UTC by miohtama

How to pass the password to the PSQL connection is not obvious from the current documentation. 
Add a basic example with links to the more documentation.

2021-12-03 08:17 UTC, dlax requested changes
@miohtama, thank you for your contribution!

@blogh, what do you think about this addition?

2021-12-03 08:17 UTC, dlax commented on README.md
> +supported by `psycopg2` library.
It's not specific to psycopg2, it's just libpq:
```suggestion
supported by `libpq`.
```

2021-12-03 11:53 UTC, blogh commented
This is a libpq feature and there are many different ways to do this.

I'd rather have this in the FAQ part and would prefer something like :

> pg_activity uses `libpq` to access to PostgreSQL. All the traditional methods are available. 
>
> You can pass the password for the database connection in a [password file](https://www.postgresql.org/docs/current/libpq-pgpass.html). Information can also be given
> via [PostgreSQL's environment variables](https://www.postgresql.org/docs/current/libpq-envars.html) (PGPASSFILE or PGPASSWORD) or via the [connection string parameters](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS).
>
> The password file is preferred since it's more secure (security is deferred to the OS). Please avoid password in connection string at all cost.

2021-12-03 11:54 UTC, blogh commented
Also : @miohtama, thank you for your contribution :)

2021-12-13 13:12 UTC, blogh commented
Are you guys ok with this ? If so I can do the PR.

2021-12-13 13:19 UTC, dlax commented
> Are you guys ok with this ? If so I can do the PR.

Yes.

2021-12-17 09:18 UTC, merged

2021-12-17 09:18 UTC, blogh commented
Pushed it that way. 

@miohtama, thanks for the patch
@dlax, thanks for reviewing