Update README.md
dalibo/pg_activity pull request #315
Opened 2022-09-19 19:47 UTC by blogh

The main page has not been updated for a while. This patch updates it with new:

* parameters
* hotkeys
* description
* screenshot

2022-09-20 06:52 UTC, dlax requested changes
The new screenshot seems very wide and I fear it'd be hard to read when included in the README which renders quite narrow. Perhaps you can resize your terminal before doing the screenshot so that the process rows fill the whole height? Also, can you exclude the terminal menu bar?

2022-09-20 06:52 UTC, dlax commented on README.md
> +Otherwise, `pg_activity` can fallback to a degraded mode where some data like
```suggestion
Otherwise, `pg_activity` can fall back to a degraded mode where some data like
```

2022-09-20 08:22 UTC, blogh commented
I retook the screen with another color palette and reduce the overall size.

2022-09-20 12:39 UTC, dlax commented
The image is blurry; and there is still the menu and scroll bar from your terminal.

Sorry to be picky on this, but I took some care to make the previous screenshot look nice and I'd thus appreciate if we keep the same "quality"...

2022-09-21 07:02 UTC, dlax commented
@blogh, I have pushed here a screenshot I just made; it's similar to the previous one, using `--no-app-name --no-user --no-client` options so that it's narrower. It's indeed wider than the previous one, but I don't think we can work around this as there is no much more information to display. I have verified that it renders fine on github within the README.

2022-09-21 07:03 UTC, dlax approved these changes

2022-09-21 07:03 UTC, dlax commented
@blogh, if you're okay with it, please go ahead and merge (possibly squashing commits).

2022-09-21 07:23 UTC, merged

2022-09-21 07:25 UTC, blogh commented
thanks for the fix